In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/carPriceTrendAnalysis.xlsx")

In [ ]:
df.head()

,Unnamed: 0,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226 kms",Diesel,Manual,1st Owner,2017,1956 cc,5 Seats
1,1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248 kms",Petrol,Automatic,1st Owner,2021,1330 cc,5 Seats
2,2,Toyota Camry 2.5 G,16.40 Lakh,"60,343 kms",Petrol,Automatic,1st Owner,2016,2494 cc,5 Seats
3,3,Honda Jazz VX CVT,7.77 Lakh,"26,696 kms",Petrol,Automatic,1st Owner,2018,1199 cc,5 Seats
4,4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414 kms",Petrol,Manual,1st Owner,2016,1199 cc,5 Seats

In [ ]:
df.dtypes

Unnamed: 0              int64
car_name               object
car_prices_in_rupee    object
kms_driven             object
fuel_type              object
transmission           object
ownership              object
manufacture             int64
engine                 object
Seats                  object
dtype: object

In [ ]:
df=df.drop(columns='Unnamed: 0',axis=1)

In [ ]:
df['kms_driven']=df['kms_driven'].str.replace("kms","")

In [ ]:
df['ownership']=df['ownership'].str.replace("st","").str.replace("Owner"," ").str.replace("nd","").str.replace("rd","").str.replace("th","")

In [ ]:
df['engine']=df['engine'].str.replace("cc","")

In [ ]:
df['Seats']=df['Seats'].str.replace("Seats","")

In [ ]:
df

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,Jeep Compass 2.0 Longitude Option BSIV,10.03 Lakh,"86,226",Diesel,Manual,1,2017,1956,5
1,Renault Duster RXZ Turbo CVT,12.83 Lakh,"13,248",Petrol,Automatic,1,2021,1330,5
2,Toyota Camry 2.5 G,16.40 Lakh,"60,343",Petrol,Automatic,1,2016,2494,5
3,Honda Jazz VX CVT,7.77 Lakh,"26,696",Petrol,Automatic,1,2018,1199,5
4,Volkswagen Polo 1.2 MPI Highline,5.15 Lakh,"69,414",Petrol,Manual,1,2016,1199,5
...,...,...,...,...,...,...,...,...,...
5507,BMW X1 sDrive 20d xLine,28.90 Lakh,"45,000",Diesel,Automatic,1,2018,2995,7
5508,BMW M Series M4 Coupe,64.90 Lakh,"29,000",Petrol,Automatic,2,2015,1968,5
5509,Jaguar XF 2.2 Litre Luxury,13.75 Lakh,"90,000",Diesel,Automatic,2,2013,2755,5
5510,BMW 7 Series 730Ld,29.90 Lakh,"79,000",Diesel,Automatic,3,2015,2967,6
5511,BMW 5 Series 520d M Sport,31.90 Lakh,"42,000",Diesel,Automatic,2,2017,1991,5

In [ ]:
df=df.dropna()

In [ ]:
for col in ['kms_driven', 'ownership', 'engine', 'Seats']:
    try:
        df[col] = df[col].astype('int')
    except:
        df[col] = df[col]

In [ ]:
m=[]
for i in df['kms_driven']:
  d=i.replace(',','')
  a=d.strip()
  m.append(int(d))
print(m)

[86226, 13248, 60343, 26696, 69414, 49719, 43688, 14470, 21429, 31750, 38203, 110284, 10381, 32378, 38906, 59313, 85672, 34971, 35894, 56000, 56568, 48872, 17346, 15414, 21239, 62361, 79329, 11945, 51324, 5717, 46417, 100161, 35424, 51085, 30983, 32681, 57581, 39821, 21186, 34972, 46623, 18557, 58463, 5000, 66000, 14000, 61000, 65392, 37000, 9000, 32000, 68000, 13000, 30000, 34300, 45000, 37000, 50000, 105241, 54000, 19600, 48000, 69500, 71000, 48894, 46257, 78264, 42451, 131861, 128004, 150349, 29033, 99000, 47000, 35000, 58000, 48000, 45000, 60000, 23000, 45000, 45000, 58000, 48000, 18000, 16000, 24000, 36000, 35000, 64000, 72000, 29900, 20000, 160000, 16000, 17000, 111000, 38000, 32000, 67000, 50000, 110000, 51000, 83000, 38000, 58000, 36000, 23500, 60000, 18000, 36500, 25000, 20500, 30000, 59000, 80000, 50000, 32000, 120000, 33000, 6900, 4500, 51000, 12000, 37000, 35000, 80000, 60000, 10000, 59385, 51000, 74000, 29000, 12200, 40000, 58000, 75000, 72000, 23400, 59300, 72000, 67000, 33500, 17000, 33000, 49000, 26000, 14500, 10000, 15001, 55000, 38000, 110000, 65413, 45000, 44000, 40000, 49000, 19000, 56000, 65000, 27680, 27305, 10793, 12000, 44000, 63000, 87000, 61000, 72000, 70000, 58000, 90000, 19000, 72159, 78000, 58000, 72000, 56000, 73000, 28840, 51500, 41370, 41266, 31740, 77876, 9500, 28387, 120000, 20000, 30686, 120000, 184000, 40000, 55000, 38000, 40000, 60000, 110000, 143000, 110000, 58000, 65000, 50000, 55000, 19500, 78000, 58000, 91000, 30000, 44153, 21000, 19000, 27300, 31001, 50000, 77000, 53000, 20000, 72000, 26000, 66000, 69619, 30000, 61000, 31000, 66000, 7700, 9000, 60000, 110000, 51001, 56207, 58000, 73290, 44283, 48000, 107500, 80000, 90000, 10000, 120000, 120000, 90000, 46000, 28000, 24000, 23000, 24300, 51000, 6000, 12600, 3500, 120000, 5000, 120000, 40000, 96000, 67000, 72000, 89000, 64000, 120000, 42000, 55000, 30000, 86500, 59000, 15000, 70000, 50000, 110000, 13700, 25000, 20000, 70000, 35000, 26629, 20000, 33000, 25000, 55291, 58500, 15000, 90000, 64000, 132596, 99673, 24374, 69828, 72820, 20785, 31172, 24395, 11050, 123394, 105053, 10283, 2443, 44000, 68000, 72000, 38000, 65000, 43000, 52000, 117000, 84000, 45080, 39341, 133000, 54112, 14824, 82500, 17922, 13000, 85000, 67000, 35000, 53000, 598, 75727, 7000, 62403, 44487, 24000, 47000, 31212, 17776, 31837, 39000, 78000, 31000, 115986, 73029, 25000, 74809, 33560, 40821, 58000, 75991, 136432, 70229, 83000, 51915, 63100, 54000, 9000, 46833, 78744, 79542, 96000, 13000, 44521, 29927, 48019, 27311, 14000, 64640, 96505, 90479, 3500, 42374, 45879, 120000, 89680, 99000, 90000, 27000, 79776, 67000, 108000, 58000, 32067, 52187, 17100, 9562, 36388, 45000, 36149, 20155, 51904, 54000, 31727, 73986, 7100, 5397, 65000, 90000, 80000, 91000, 69000, 89000, 95254, 51000, 62000, 120000, 2000, 46000, 65000, 22248, 40000, 73000, 54000, 90000, 15000, 30000, 26000, 155000, 29366, 28211, 40000, 54000, 82000, 117000, 111000, 108000, 4000, 290000, 35000, 13000, 60000, 90000, 16975, 11000, 59000, 46000, 80000, 25000, 54801, 75000, 130000, 71000, 70000, 14115, 30000, 63170, 80000, 47253, 56117, 14324, 27600, 38391, 49000, 45000, 68000, 67000, 80000, 62000, 50000, 100000, 75000, 120000, 37000, 64000, 79000, 80000, 14000, 28217, 90000, 120000, 26000, 100000, 50000, 70000, 80000, 157000, 15550, 80000, 59432, 53047, 46464, 70000, 23000, 30000, 22000, 35000, 80000, 100000, 95000, 100000, 50000, 64000, 15509, 43203, 80000, 50000, 40000, 111000, 73000, 220000, 11717, 46000, 15000, 110000, 66968, 120000, 70000, 47000, 110000, 81000, 70000, 12662, 14000, 56000, 54000, 63000, 40000, 60000, 80000, 120000, 15000, 295000, 60000, 50000, 55000, 77000, 33389, 17526, 15757, 8183, 32590, 45423, 52481, 22915, 72123, 37965, 27651, 92771, 51956, 34048, 47000, 60000, 43000, 58596, 70000, 69000, 50152, 62164, 49929, 60393, 46281, 53201, 80056, 76175, 51493, 63141, 37057, 60865, 45407, 52652, 42923, 56052, 42923, 32733, 62207, 48352, 57080, 43168, 69517, 54166, 67000, 21000, 67200, 69000, 46000, 42000, 59000, 50000, 115000, 68000, 29000, 68000, 43000, 23000, 68000, 31000, 60000, 59000, 61000, 52000, 41000, 40008, 38170, 47000, 42332, 34000, 13000, 10000, 37000, 39000, 129000, 20000, 39000, 72000, 63000, 90000, 66000, 27000, 94000, 26000, 1199, 51000, 83800, 75000, 13000, 43136, 18100, 46000, 32000, 50000, 58000, 86108, 55630, 63723, 33000, 75270, 80502, 39520, 38000, 116509, 76398, 36000, 64803, 34453, 17348, 51000, 58000, 102732, 90592, 22000, 10000, 22000, 65000, 59000, 42306, 26000, 71000, 44000, 11000, 19062, 28000, 78000, 28148, 83634, 36845, 57000, 43417, 4800, 58955, 30000, 45005, 42032, 89653, 67000, 75765, 74007, 63457, 57000, 52217, 28000, 69000, 75000, 71033, 92860, 48000, 76000, 26000, 23000, 77132, 52000, 30000, 58000, 118971, 51000, 60000, 103000, 48150, 65000, 78598, 53633, 60000, 6701, 36000, 63000, 70000, 71760, 41000, 84612, 70000, 124183, 33647, 96000, 42000, 12800, 72504, 47756, 21000, 80425, 41643, 37125, 34511, 87013, 149232, 82145, 28000, 75805, 13093, 47330, 21000, 59000, 48230, 69240, 18000, 79000, 109100, 33000, 900, 49000, 55000, 17700, 90000, 55700, 102000, 101000, 72000, 39000, 72000, 91717, 60000, 61828, 98554, 112696, 11000, 80000, 9329, 64419, 68000, 91892, 50827, 69167, 7000, 25000, 84489, 35343, 41000, 100527, 54239, 26457, 97000, 67231, 74228, 55362, 58000, 80896, 36398, 50227, 31000, 17359, 2263, 81437, 34000, 80228, 65911, 39898, 11000, 25000, 10218, 88119, 64000, 14572, 66512, 66357, 60000, 91865, 31409, 76247, 52000, 48267, 31441, 59564, 80000, 65115, 46149, 65598, 72000, 72350, 18959, 80078, 58000, 49613, 80002, 16194, 55617, 38409, 68045, 7342, 27914, 8639, 11069, 73971, 70379, 19108, 37842, 120000, 24000, 35500, 15000, 9900, 7600, 57826, 91216, 13731, 60477, 105911, 18072, 53608, 17790, 24154, 24744, 38985, 41050, 61714, 20092, 74811, 8702, 34039, 98285, 72000, 50000, 120000, 76813, 80000, 20000, 24000, 43200, 42000, 49000, 195000, 12200, 23000, 17000, 70000, 75000, 72521, 19000, 37233, 2682, 115000, 24900, 74000, 25102, 16700, 7500, 60000, 113000, 37800, 56000, 100000, 250, 80000, 4000, 3731, 4028, 70000, 13000, 65000, 73000, 77200, 15000, 120000, 45200, 75200, 25000, 80000, 160000, 65150, 65000, 80000, 50000, 108000, 45000, 139000, 120000, 29000, 80105, 60000, 70000, 45000, 110000, 120000, 72568, 40000, 81000, 30000, 100000, 7000, 18770, 85680, 61548, 25000, 100000, 80000, 5000, 12000, 84250, 120000, 35000, 37000, 72000, 72000, 80250, 50000, 75000, 48763, 34142, 8900, 25000, 25000, 70000, 28000, 21000, 40000, 40000, 65500, 90000, 179000, 40000, 27000, 70000, 60000, 40000, 10000, 40000, 29081, 30000, 66000, 80000, 6200, 20000, 40000, 80000, 20000, 60000, 34000, 30000, 120000, 50000, 38000, 85000, 25000, 120000, 1400, 65500, 380000, 50000, 40000, 100000, 5000, 90000, 100000, 50000, 110000, 120000, 116000, 25000, 75000, 120000, 70000, 90000, 120000, 25000, 263000, 110000, 10000, 137535, 90000, 35000, 40000, 39000, 73200, 88500, 49000, 45000, 114862, 147947, 4391, 115549, 38738, 85762, 27987, 141918, 39558, 68456, 86000, 29782, 95046, 133053, 151537, 91437, 11615, 85471, 82591, 73000, 68000, 73592, 114361, 84193, 57000, 48727, 6510, 33088, 151434, 21166, 106647, 37930, 128281, 168062, 13333, 151026, 134521, 132996, 29000, 19534, 88673, 32272, 26850, 120426, 21796, 118881, 32039, 124763, 201197, 81672, 20248, 73639, 82028, 32375, 182048, 158108, 74176, 17805, 105209, 72792, 93411, 51954, 199085, 213709, 134698, 82983, 81678, 50789, 46994, 19528, 68315, 69720, 110655, 87100, 124012, 92251, 61127, 141083, 61802, 147215, 74295, 66290, 92485, 57563, 30675, 58835, 122571, 116064, 128396, 47000, 10000, 37275, 44000, 39000, 97767, 32000, 53931, 73818, 27200, 46365, 82496, 73656, 92530, 68364, 30224, 88658, 26396, 60020, 55107, 3925, 21949, 41899, 43000, 20000, 24000, 39356, 18000, 40000, 30555, 119878, 84557, 96528, 44081, 6494, 118631, 47133, 94025, 68841, 31952, 66518, 26684, 38280, 96392, 92613, 40011, 98772, 38931, 82392, 96805, 68307, 30404, 36438, 115206, 104537, 29827, 55000, 68000, 80000, 55000, 67885, 28000, 48421, 49000, 75000, 55000, 6357, 24237, 10282, 111337, 64104, 42234, 80000, 2294, 38736, 130432, 10000, 44000, 68000, 38000, 35000, 65000, 12001, 36000, 43000, 7500, 56500, 30000, 63500, 26500, 38500, 65000, 44500, 15500, 20500, 65000, 64593, 63203, 60500, 50000, 43000, 31458, 70000, 70372, 129325, 59290, 15000, 75000, 94002, 90004, 47000, 83005, 62500, 67000, 64000, 39889, 81250, 9900, 43000, 2400, 7600, 79004, 99300, 80000, 40000, 87002, 94002, 82005, 20000, 95004, 68753, 62500, 62000, 85000, 58000, 55500, 49000, 54000, 32500, 33500, 17000, 38000, 16500, 2000, 29000, 24000, 37229, 19000, 90928, 39000, 44000, 12000, 86483, 20000, 49000, 12000, 26000, 40252, 97947, 38000, 150715, 102820, 109403, 11000, 37377, 84728, 53548, 20000, 29397, 30346, 42119, 120450, 148393, 21549, 85000, 90468, 20900, 19234, 24900, 73269, 48101, 24001, 7500, 9701, 27133, 18270, 56000, 50001, 56681, 2755, 46201, 85001, 64836, 4000, 24057, 49559, 10289, 64000, 54001, 27779, 70000, 70000, 49000, 115000, 13000, 35000, 3900, 63000, 15000, 60000, 23000, 6000, 25000, 64000, 17000, 40000, 30000, 79000, 26000, 25102, 65000, 35000, 33000, 29000, 45000, 25500, 48000, 100000, 29000, 83000, 57000, 59000, 45000, 69000, 69000, 79000, 44000, 69000, 68000, 60000, 86000, 39000, 12000, 85000, 120000, 90000, 80000, 34000, 72000, 18000, 11000, 60625, 68000, 75000, 70000, 73000, 65000, 70011, 40000, 67011, 103000, 50000, 7000, 30000, 44000, 28500, 8000, 60000, 70000, 80000, 25000, 2000, 35000, 26000, 12000, 13001, 60000, 37000, 27200, 46365, 82496, 73656, 92530, 68364, 30224, 88658, 26396, 60020, 55107, 3925, 21949, 41899, 30000, 28000, 20000, 24000, 13000, 54000, 30555, 119878, 84557, 96528, 44081, 6494, 118631, 47133, 94025, 68841, 31952, 66518, 26684, 38280, 96392, 92613, 40011, 98772, 38931, 82392, 96805, 68307, 30404, 36438, 115206, 104537, 29827, 9200, 39356, 55000, 80000, 55000, 18000, 43000, 1000, 67885, 40000, 48421, 110000, 49000, 75000, 71000, 78000, 68000, 94944, 6357, 24237, 28000, 10282, 111337, 127429, 55000, 61034, 76036, 65000, 80000, 64104, 116378, 42234, 10000, 49812, 2294, 94679, 35000, 57122, 25122, 60000, 36000, 38736, 130432, 44000, 30000, 68000, 38000, 65000, 65000, 12001, 23000, 65000, 43000, 25000, 7500, 50000, 36000, 86000, 56500, 70000, 68000, 63500, 26500, 15000, 38500, 44500, 15500, 47000, 12000, 20500, 64593, 64000, 70000, 63203, 60500, 9900, 25000, 65000, 68500, 43000, 70000, 150000, 7600, 31458, 70372, 129325, 39000, 17000, 20000, 57000, 40000, 46000, 18000, 59290, 20000, 18000, 56000, 66000, 43000, 67000, 75000, 47000, 8800, 94002, 12000, 75000, 62000, 90004, 83005, 47000, 49000, 70000, 62500, 49036, 17000, 67000, 39889, 2000, 81250, 43000, 19000, 29000, 2400, 79004, 28000, 99300, 80000, 87002, 19000, 94002, 82005, 95004, 25000, 68753, 62500, 85000, 12000, 58000, 55500, 54000, 12000, 32500, 33500, 60000, 38000, 120000, 64000, 59000, 11000, 12023, 30000, 20000, 38000, 16500, 29000, 24000, 37229, 100000, 85000, 90928, 39000, 78000, 24900, 44000, 86483, 20000, 7500, 49000, 26000, 65000, 56000, 40252, 97947, 150715, 102820, 109403, 37377, 4000, 84728, 53548, 29397, 64000, 30346, 42119, 120450, 70000, 59534, 90000, 63001, 153000, 65000, 60000, 17000, 55000, 24000, 102000, 40000, 92195, 13780, 24700, 41000, 18000, 7000, 39600, 39500, 11800, 77000, 99000, 177000, 43000, 40000, 65000, 39000, 48000, 77000, 52000, 27000, 47000, 42000, 42000, 48000, 59000, 27000, 44000, 5000, 78000, 57000, 48000, 56000, 15000, 77000, 60000, 65000, 61985, 19000, 30000, 41000, 6834, 112160, 16118, 47000, 80000, 24000, 46000, 30000, 30000, 31000, 46000, 44000, 40000, 39000, 63759, 29000, 42000, 37000, 40000, 33000, 26000, 24000, 156596, 98778, 145000, 26000, 60000, 560000, 45000, 27000, 43000, 37000, 46000, 51366, 77331, 77783, 44000, 56276, 44408, 80000, 20000, 19000, 73500, 28783, 43000, 117500, 46352, 84123, 22773, 20000, 77075, 38000, 70000, 40000, 20000, 60000, 19521, 19800, 50000, 50000, 37000, 40000, 10700, 31800, 32400, 4700, 33500, 54800, 44000, 19000, 22000, 12900, 22700, 69000, 60000, 9500, 15000, 19000, 3500, 81721, 109656, 87955, 50000, 12990, 75099, 120000, 70000, 90000, 10000, 44000, 29500, 81200, 50000, 141383, 34392, 90000, 47681, 25900, 120000, 68952, 41525, 15000, 11000, 29990, 25000, 20000, 90000, 80000, 50000, 90000, 70000, 20000, 25000, 60000, 56000, 53000, 10000, 110000, 99990, 68000, 68500, 50599, 54431, 65855, 113706, 40000, 100000, 36700, 40000, 50000, 50000, 40000, 135000, 40000, 15000, 39000, 60000, 120000, 60000, 45000, 23000, 46952, 35000, 70000, 90000, 35000, 19400, 80000, 30900, 30000, 77000, 36000, 19000, 70000, 85000, 23000, 75000, 85000, 50000, 50000, 60000, 60000, 36000, 120000, 70000, 94000, 9000, 135000, 70000, 39000, 50000, 8000, 50000, 14000, 40000, 196000, 95000, 48632, 90000, 95000, 55000, 18000, 29000, 5000, 25000, 41000, 63463, 20000, 69852, 29584, 27514, 30339, 39386, 64671, 30670, 46086, 70346, 50000, 80000, 58365, 12000, 58182, 325000, 127152, 98492, 23000, 45000, 63001, 72000, 26000, 46000, 140000, 3500, 120000, 39000, 79100, 60000, 30000, 46000, 65232, 106865, 49900, 100000, 110000, 9000, 15000, 45000, 100000, 80000, 80000, 11000, 50000, 90000, 90000, 93500, 32000, 60000, 70000, 70000, 18999, 110000, 145000, 60000, 50000, 70000, 48000, 80000, 40000, 50000, 158763, 35000, 90000, 120000, 60000, 70000, 97320, 118393, 24774, 50000, 13800, 147000, 50000, 50000, 30000, 56001, 60000, 32976, 6830, 76018, 65841, 29943, 35383, 90000, 50000, 63723, 75270, 80502, 39520, 60000, 79000, 66000, 116509, 76398, 55000, 61000, 80000, 64803, 34453, 17348, 102732, 90592, 80000, 19062, 65000, 45000, 83634, 103000, 42032, 89653, 57000, 80000, 82000, 50000, 98000, 71033, 95000, 68000, 98000, 92860, 77132, 118971, 28000, 71760, 84612, 124183, 47756, 65000, 37125, 87013, 149232, 82145, 75805, 73000, 91717, 61828, 98554, 112696, 9329, 64419, 91892, 50827, 69167, 84489, 35343, 100527, 54239, 26457, 67231, 74228, 55362, 80896, 2263, 25000, 14572, 91865, 77000, 36109, 72000, 73500, 212171, 73079, 47791, 89982, 100694, 42788, 53127, 47832, 119570, 13251, 10514, 58613, 46883, 56000, 210000, 103000, 86000, 76000, 76000, 40000, 50000, 20000, 74000, 120000, 70000, 87000, 110000, 61000, 21300, 110000, 11400, 30000, 120000, 98000, 50000, 100000, 73000, 90786, 14801, 70000, 40000, 120000, 77000, 90000, 100000, 175000, 155000, 170000, 70000, 25000, 72000, 8500, 120000, 100000, 10000, 70000, 32000, 70000, 110000, 110000, 80000, 90000, 50000, 60000, 60000, 50000, 120000, 108000, 60000, 50000, 110000, 60000, 75000, 50000, 69000, 135000, 24000, 72000, 126000, 14000, 61000, 60000, 5000, 25000, 50000, 60000, 15000, 96000, 120000, 70000, 22045, 110000, 70000, 141292, 93313, 20798, 91849, 15758, 80000, 121000, 83114, 76357, 10000, 90000, 50000, 40000, 110000, 25000, 120000, 120000, 120000, 100000, 110000, 40000, 80000, 100000, 50000, 46000, 87000, 75000, 110000, 64000, 77000, 110000, 100000, 50000, 62000, 120000, 120000, 90000, 80000, 120000, 15000, 80000, 90000, 10000, 70000, 100000, 80000, 160000, 48000, 90000, 50000, 107000, 30000, 35000, 70000, 69146, 67000, 99452, 28330, 50960, 13575, 85000, 85000, 7020, 3638, 4792, 11193, 67008, 81000, 80000, 17000, 22000, 31000, 72000, 68000, 32935, 16000, 72224, 35667, 58602, 40102, 70518, 133876, 7309, 209362, 105685, 58415, 69411, 31356, 112640, 49289, 86208, 40530, 44877, 92170, 94301, 5140, 86261, 240521, 74000, 33000, 19900, 105014, 27174, 68671, 100000, 78452, 51200, 138314, 66614, 117000, 24000, 135000, 4595, 58503, 39000, 71000, 79369, 100000, 10000, 22000, 21321, 8826, 14000, 20000, 40000, 25000, 30000, 80000, 98725, 59632, 71230, 50000, 117302, 78318, 98836, 88235, 120000, 110000, 84738, 60000, 38238, 114996, 68269, 15000, 101000, 90000, 103000, 66000, 90623, 100000, 71000, 70000, 38431, 110000, 110000, 249535, 59858, 89506, 76365, 120000, 35000, 25000, 81000, 98328, 50000, 52548, 80000, 50000, 10000, 60000, 15000, 100000, 27726, 180000, 40000, 80252, 90000, 75000, 120000, 57988, 85000, 62000, 63000, 65000, 65000, 99000, 80000, 5000, 110000, 142366, 170000, 54000, 15000, 42550, 110000, 70000, 90000, 50540, 35000, 30000, 90000, 25000, 100000, 90000, 33783, 50000, 30000, 50000, 25000, 40000, 68414, 91777, 79399, 70683, 37820, 25943, 63470, 56500, 46364, 138571, 15000, 150000, 44357, 20000, 60152, 10000, 25000, 50000, 44599, 289000, 80000, 120000, 60000, 60000, 70000, 90000, 156000, 35000, 78000, 40000, 40000, 25000, 80000, 77450, 170000, 15000, 132000, 58000, 60000, 40000, 80000, 70000, 55726, 92916, 120000, 120000, 110000, 90000, 120000, 50000, 8000, 70000, 60400, 69824, 40000, 121000, 40000, 50000, 100000, 70000, 120000, 90000, 120000, 80000, 110000, 40000, 100000, 35700, 35000, 43000, 30000, 68000, 90000, 120000, 50000, 38800, 110000, 120000, 20439, 110000, 120000, 110000, 80000, 100000, 60000, 20000, 70000, 50000, 200000, 60000, 120000, 80000, 50000, 15000, 52552, 63565, 154659, 110000, 27850, 50000, 37000, 96384, 66070, 77500, 76504, 75763, 58028, 96909, 49229, 82113, 50140, 89034, 141692, 90000, 76407, 103535, 10048, 193707, 20987, 77000, 88000, 119000, 56000, 86000, 68000, 76000, 70354, 117000, 65000, 46865, 77932, 118215, 45873, 115596, 69218, 26192, 90992, 42322, 20064, 37418, 86102, 105192, 46895, 94135, 84278, 19150, 22803, 35864, 48007, 98057, 17222, 77960, 105812, 47180, 91865, 121761, 44540, 27713, 83354, 118587, 72318, 88579, 69509, 68012, 71250, 76268, 118649, 19319, 69826, 43274, 45950, 91649, 56936, 9000, 120422, 133659, 80295, 55259, 54996, 30903, 77385, 38733, 51242, 79385, 57304, 106188, 57778, 64011, 35315, 15000, 21461, 90000, 42512, 53580, 25000, 1619, 45000, 175000, 64000, 17000, 48000, 86000, 64000, 84000, 45000, 39000, 25000, 55000, 48000, 17001, 18000, 42000, 176000, 55352, 5000, 56231, 7000, 80000, 120000, 22000, 83000, 80000, 20000, 35000, 60000, 67000, 65000, 26000, 65000, 35000, 85000, 60000, 80000, 60000, 430000, 50000, 120000, 18000, 42130, 64000, 63000, 47000, 67000, 40000, 99000, 7500, 50000, 41000, 50000, 15000, 40000, 20000, 29000, 13000, 27000, 50000, 48000, 39000, 41000, 74988, 24494, 26000, 80000, 60000, 60000, 44304, 32000, 24531, 35000, 73000, 31000, 43000, 5000, 25000, 90000, 56150, 20000, 60000, 70000, 25000, 25000, 18000, 12000, 15000, 55000, 70000, 300000, 52314, 19000, 16937, 25000, 40000, 70000, 46000, 70000, 40000, 17500, 70000, 67000, 20000, 120000, 120000, 100000, 30000, 15000, 30000, 40000, 50000, 70000, 5000, 15000, 60000, 50000, 46000, 55000, 50000, 6400, 40000, 20000, 60000, 40000, 130000, 30000, 15000, 40000, 50000, 120000, 10000, 75000, 50000, 120000, 50000, 5000, 80000, 40000, 30000, 120000, 40000, 70000, 120000, 5000, 35000, 40000, 20000, 80000, 15000, 70000, 120000, 25000, 25000, 60000, 80000, 80000, 90000, 37000, 50000, 50000, 19493, 35000, 60000, 50000, 80000, 78527, 94000, 5000, 40000, 53128, 39959, 4768, 54004, 16570, 7869, 67640, 8934, 20241, 67343, 10065, 57628, 72375, 19328, 24941, 56441, 89865, 25919, 17363, 60726, 54842, 31916, 35457, 34640, 39398, 42919, 38359, 101875, 21976, 65531, 5044, 66906, 47547, 25347, 49712, 4781, 21716, 55160, 50788, 58475, 94321, 23907, 42060, 25258, 31043, 39057, 20484, 55517, 53234, 51007, 53755, 62144, 45130, 155124, 30730, 107488, 86336, 31253, 33235, 2258, 100169, 34000, 7000, 5900, 27398, 43259, 15016, 30686, 39543, 93913, 27729, 51501, 90147, 16419, 48368, 33193, 39260, 55212, 81674, 27321, 42815, 39977, 64669, 12603, 32500, 7169, 10482, 48111, 63210, 35289, 27352, 25572, 67967, 10834, 56000, 24000, 34000, 13000, 158066, 22543, 46767, 7848, 71245, 1923, 38463, 28000, 19000, 24500, 11400, 10400, 26000, 30000, 24000, 100004, 25373, 25635, 46982, 94989, 18322, 34364, 17893, 15224, 90228, 76279, 68861, 52816, 314273, 5439, 64164, 60834, 14700, 25000, 10000, 39000, 80000, 25000, 75656, 30000, 60000, 120000, 100000, 70000, 120000, 50000, 90000, 70000, 20000, 50000, 25000, 65000, 90000, 30000, 60000, 10000, 30000, 32000, 10000, 110000, 120000, 80000, 53000, 80000, 50000, 40000, 60000, 60000, 40000, 50000, 10000, 80000, 60000, 400000, 12000

In [ ]:
df['kms_driven']=m

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5512 entries, 0 to 5511
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             5512 non-null   object
 1   car_prices_in_rupee  5512 non-null   object
 2   kms_driven           5512 non-null   int64
 3   fuel_type            5512 non-null   object
 4   transmission         5512 non-null   object
 5   ownership            5512 non-null   int64
 6   manufacture          5512 non-null   int64
 7   engine               5512 non-null   int64
 8   Seats                5512 non-null   int64
dtypes: int64(5), object(4)
memory usage: 430.6+ KB

In [ ]:
main=[]
for i in df['car_prices_in_rupee']:
  if 'Crore' in str(i):
    c=i.replace('Crore','')
    main.append(int(float(c)*100)*100000)
  elif 'Lakh' in str(i):
    l=i.replace('Lakh','')
    main.append(int(float(l)*100000))
  else:
    main.append(i)
print(main)

[1002999, 1283000, 1639999, 777000, 515000, 766000, 758000, 1160000, 699000, 753000, 643000, 543000, 861999, 1678000, 1002999, 563000, 667000, 673000, 321000, 850000, 434000, 311000, 370000, 1588000, 541000, 223000, 588000, 2278000, 612000, 744000, 839000, 420000, 491000, 293000, 298000, 260000, 238000, 605000, 323000, 326000, 421000, 1553000, 1243000, 1850000, 1590000, 890000, 4300000, 600000, 2700000, 1090000, 590000, 650000, 675000, 370000, 525000, 725000, 850000, 1400000, 1500000, 1390000, 890000, 1689999, 1390000, 1500000, 4500000, 153000, 509000, 546000, 273000, 180000, 110000, 369000, 1350000, 275000, 550000, 975000, 400000, 475000, 190000, 465000, 459999, 325000, 525000, 625000, 4000000, 1675000, 1000000, 1789999, 1390000, 610000, 775000, 459999, 2091000, 310000, 565000, 900000, 4200000, 2850000, 550000, 450000, 675000, 180000, 775000, 550000, 2400000, 1325000, 1100000, 1050000, 650000, 2500000, 600000, 3100000, 1575000, 450000, 590000, 1450000, 380000, 2100000, 261000, 11000000, 4200000, 2250000, 4200000, 1975000, 950000, 1451000, 300000, 459999, 915000, 550000, 1700000, 990000, 851000, 2750000, 550000, 951000, 1989999, 3550000, 550000, 390000, 890000, 451000, 725000, 1275000, 690000, 675000, 565000, 1000000, 1975000, 1700000, 975000, 650000, 400000, 475000, 280000, 430000, 490000, 651000, 1751000, 391000, 375000, 490000, 1825000, 3300000, 5600000, 1499000, 1199000, 650000, 190000, 625000, 1651000, 225000, 130000, 1250000, 925000, 590000, 690000, 890000, 4250000, 290000, 890000, 690000, 480000, 875000, 990000, 615000, 2050000, 625000, 2700000, 450000, 4250000, 100000, 600000, 400000, 625000, 575000, 2350000, 135000, 300000, 210000, 125000, 475000, 550000, 1700000, 349000, 7000000, 925000, 390000, 1025000, 1125000, 725000, 3450000, 1400000, 1950000, 3400000, 310000, 130000, 650000, 275000, 350000, 890000, 425000, 2200000, 430000, 211000, 975000, 625000, 7200000, 1750000, 340000, 110000, 1675000, 2100000, 2690000, 650000, 790000, 425000, 340000, 99999, 200000, 775000, 215000, 237000, 55000, 425000, 575000, 825000, 690000, 775000, 790000, 1490000, 1725000, 3700000, 229999, 750000, 135000, 695000, 785000, 325000, 790000, 321000, 330000, 200000, 540000, 270000, 495000, 1000000, 1050000, 310000, 1200000, 600000, 300000, 925000, 570000, 1100000, 1800000, 100000, 4350000, 4650000, 5395000, 6175000, 2795000, 1650000, 7250000, 650000, 1300000, 400000, 154000, 418000, 392000, 594000, 3724000, 588000, 451999, 1825000, 774000, 421000, 844000, 2199000, 3100000, 994999, 975000, 225000, 650000, 1875000, 425000, 745000, 825000, 204000, 470000, 330000, 321000, 819999, 925000, 1349000, 12300000, 1675000, 575000, 745000, 345000, 2075000, 892000, 1889999, 858000, 453000, 3900000, 2850000, 190000, 3365000, 658000, 2580000, 120000, 1185000, 388000, 392000, 635000, 244000, 272000, 286000, 1575000, 163000, 178000, 84778, 1725000, 111000, 550000, 4800000, 4550000, 325000, 525000, 490000, 459999, 1325000, 380000, 547000, 1975000, 675000, 2050000, 315000, 499000, 3200000, 965000, 855000, 710000, 572000, 470000, 1275000, 110000, 5975000, 1465000, 5400000, 1475000, 944999, 2275000, 1950000, 5875000, 1939999, 1810000, 975000, 1775000, 1695000, 1675000, 725000, 1565000, 1445000, 1425000, 1395000, 4950000, 700000, 475000, 700000, 2375000, 1750000, 825000, 1050000, 395000, 1235000, 2575000, 685000, 944999, 425000, 4300000, 575000, 1145000, 260000, 2725000, 1820000, 2795000, 350000, 3425000, 675000, 1675000, 2450000, 1025000, 465000, 1125000, 795000, 330000, 685000, 3590000, 1795000, 490000, 975000, 3375000, 575000, 985000, 225000, 135000, 750000, 725000, 200000, 865000, 310000, 1000000, 1044999, 750000, 3995000, 295000, 3295000, 295000, 3395000, 3445000, 1948999, 3245000, 775000, 695000, 825000, 775000, 675000, 250000, 695000, 275000, 650000, 1745000, 3100000, 695000, 180000, 475000, 525000, 140000, 185000, 1044999, 3000000, 500000, 875000, 362000, 180000, 1745000, 800000, 1395000, 1044999, 775000, 120000, 1075000, 3450000, 4875000, 919999, 1050000, 200000, 350000, 260000, 180000, 525000, 1085000, 965000, 266000, 1795000, 459999, 994999, 120000, 1675000, 535000, 5650000, 648000, 595000, 1425000, 500000, 735000, 755000, 250000, 495000, 225000, 1595000, 1025000, 575000, 996000, 775000, 520000, 210000, 600000, 650000, 585000, 292000, 650000, 425000, 445000, 675000, 533000, 536000, 564000, 278000, 583000, 699000, 900000, 453000, 601000, 575000, 530000, 495000, 1027999, 399000, 6350000, 1400000, 4775000, 811000, 4850000, 675000, 227999, 513999, 819999, 491000, 588000, 553000, 710000, 320000, 601000, 532000, 651000, 852000, 1110000, 1183000, 1060000, 919999, 651000, 844000, 211000, 603000, 600000, 630000, 823000, 618000, 285000, 425000, 390000, 675000, 425000, 2089999, 490000, 2411000, 490000, 395000, 770000, 575000, 545000, 3000000, 185000, 540000, 325000, 360000, 245000, 1500000, 585000, 495000, 1225000, 725000, 975000, 285000, 550000, 1125000, 399000, 1000000, 994999, 1921000, 399000, 465000, 1100000, 9100000, 2550000, 1950000, 650000, 890000, 1125000, 3950000, 1975000, 545000, 225000, 625000, 7000000, 4250000, 345000, 1675000, 735000, 158000, 250000, 134000, 1325000, 340000, 264000, 224000, 1800000, 463000, 1085000, 2674000, 604000, 252000, 575000, 1465000, 565000, 600000, 400000, 4375000, 1550000, 7250000, 325000, 1625000, 495000, 465000, 160000, 1175000, 3700000, 470000, 835000, 3200000, 390000, 398000, 711000, 781000, 825000, 775000, 300000, 2025000, 911000, 599000, 436000, 2650000, 625000, 1250000, 590000, 625000, 375000, 1595000, 285000, 4650000, 393000, 199000, 1495000, 2250000, 1115000, 699000, 300000, 575000, 475000, 1035000, 135000, 624000, 59000, 165000, 349000, 2050000, 155000, 515000, 1511000, 1490000, 994999, 1950000, 1000000, 273000, 145000, 913000, 1864999, 593000, 765000, 434999, 2925000, 1725000, 200999, 341000, 9500000, 390000, 140000, 375000, 570000, 352000, 271000, 254000, 1545000, 282000, 1215000, 399000, 881000, 2929000, 550000, 315000, 1739999, 595000, 350000, 685000, 1000000, 765000, 580000, 636000, 1350000, 180000, 199000, 275000, 2200000, 675000, 385000, 190000, 331000, 317000, 238000, 462000, 2950000, 90000, 2418000, 666000, 2674000, 563000, 479000, 553000, 6575000, 400000, 99205, 1182000, 2950000, 236000, 367000, 313000, 2174000, 486000, 121000, 451000, 941000, 179000, 1775000, 375000, 4445000, 695000, 1270000, 665000, 2474000, 1925000, 715000, 795000, 6500000, 800000, 675000, 305000, 2185000, 1008000, 421000, 565000, 1165000, 566000, 1785000, 245000, 1911000, 361000, 944999, 365000, 840000, 285000, 465000, 321000, 3575000, 565000, 725000, 421000, 650000, 649000, 830000, 980000, 1235000, 940000, 325000, 926000, 944999, 1260000, 1185000, 969000, 515000, 999000, 899000, 225000, 5650000, 2500000, 6100000, 7400000, 7450000, 890000, 625000, 999000, 750000, 639000, 925000, 699000, 799000, 669000, 300000, 578000, 328000, 368000, 874000, 676000, 978999, 610000, 670000, 1350000, 480000, 1955000, 1074000, 125000, 4090000, 3900000, 1889999, 650000, 4400000, 180000, 1650000, 690000, 5800000, 844999, 925000, 610000, 6000000, 1150000, 550000, 409999, 7150000, 1095000, 640000, 60000, 4700000, 800000, 550000, 650000, 15800000, 300000, 3050000, 151000, 6200000, 840000, 1125000, 650000, 4775000, 330000, 170000, 525000, 11700000, 1450000, 300000, 425000, 8300000, 200000, 450000, 475000, 4600000, 459999, 900000, 850000, 5950000, 129000, 290000, 4800000, 450000, 875000, 250000, 5600000, 375000, 240000, 725000, 19200000, 105000, 365000, 800000, 6850000, 5600000, 925000, 725000, 3000000, 140000, 425000, 700000, 6600000, 690000, 180000, 800000, 2150000, 565000, 844999, 450000, 5800000, 520000, 700000, 725000, 6700000, 675000, 700000, 770000, 4250000, 650000, 570000, 315000, 2575000, 580000, 150000, 509999, 16900000, 525000, 65000, 499000, 4000000, 595000, 89000, 536000, 1095000, 1200000, 720000, 470000, 3450000, 65000, 650000, 150000, 5450000, 55000, 1150000, 45000, 4875000, 125000, 1700000, 95000, 17700000, 650000, 170000, 700000, 390000, 39000, 378000, 550000, 490000, 290000, 350000, 480000, 475000, 426000, 1400000, 400000, 120000, 160000, 100000, 430000, 175000, 270000, 400000, 100000, 370000, 403000, 1600000, 520000, 1590000, 990000, 360000, 740000, 181000, 950000, 947000, 63803, 445000, 635000, 782000, 302000, 723000, 344000, 340000, 440000, 114999, 496000, 462000, 440000, 178000, 1121000, 340000, 725000, 421000, 128000, 248000, 516000, 525000, 593000, 1043000, 665000, 245000, 547000, 250999, 276000, 301000, 469000, 493000, 259000, 393000, 290000, 5650000, 1292000, 644000, 1093000, 433000, 98497, 246000, 269000, 775000, 537000, 695000, 851000, 732000, 221000, 155000, 387000, 475000, 1328000, 1130000, 903999, 131000, 98429, 370000, 1452000, 386000, 247000, 265000, 107000, 296000, 86503, 782000, 729000, 725000, 582000, 515000, 107000, 319000, 134000, 80902, 399000, 325000, 231000, 443000, 349000, 822000, 536000, 225000, 337000, 258000, 407000, 158000, 15200000, 17500000, 254999, 4400000, 4350000, 84637, 5650000, 500000, 347000, 690000, 772000, 872000, 651000, 543000, 658000, 1261000, 585000, 1053000, 746000, 268000, 1243000, 323000, 500000, 4600000, 6100000, 5650000, 1750000, 7150000, 1375000, 315000, 478000, 243000, 536000, 1124000, 775000, 340000, 351000, 455999, 501999, 1046000, 1130000, 1053000, 790000, 377000, 286000, 1178000, 533000, 350000, 426999, 572000, 998000, 375000, 630000, 376000, 623000, 1613000, 1575000, 2450000, 2875000, 1945000, 229999, 1650000, 229999, 425000, 450000, 4050000, 471000, 1024000, 589000, 1710000, 982000, 560000, 1475000, 501999, 631000, 381000, 1150000, 3100000, 994999, 225000, 2100000, 650000, 1585000, 1425000, 1875000, 6000000, 1300000, 3675000, 1000000, 4100000, 2850000, 890000, 925000, 975000, 10000000, 4400000, 1850000, 2200000, 2900000, 6050000, 600000, 307000, 5200000, 525000, 190000, 85671, 6100000, 3790000, 1600000, 1190000, 2350000, 2900000, 475000, 1290000, 3650000, 441000, 4200000, 7400000, 525000, 1725000, 7450000, 2290000, 875000, 2190000, 5100000, 3525000, 1425000, 1425000, 4090000, 3975000, 2810000, 475000, 1575000, 894999, 699000, 620000, 4400000, 625000, 1250000, 1260000, 5800000, 2110000, 3650000, 7625000, 1889999, 3900000, 483000, 6000000, 430999, 2580000, 725000, 4990000, 193000, 900000, 575000, 4790000, 1875000, 606000, 323000, 8500000, 716000, 158000, 252999, 3965000, 858000, 367000, 324000, 4475000, 1619000, 405999, 1063000, 327000, 267000, 1339000, 2975000, 590000, 1556000, 1387000, 7150000, 875000, 1525000, 1495000, 4700000, 1948999, 1989999, 525000, 15800000, 550000, 560000, 980000, 650000, 950000, 465000, 6200000, 690000, 1695000, 2350000, 775000, 1450000, 1825000, 1349000, 835000, 4800000, 409999, 4775000, 1200000, 1895000, 894999, 11700000, 1149000, 1245000, 6600000, 8300000, 1250000, 3600000, 695000, 1875000, 260000, 1700000, 640000, 4600000, 390000, 340000, 4810000, 5950000, 4500000, 4825000, 2445000, 4800000, 285000, 200000, 590000, 5600000, 2590000, 2990000, 3490000, 6890000, 3890000, 1125000, 3100000, 825000, 1645000, 625000, 360000, 2950000, 751000, 6250000, 5650000, 465000, 1900000, 4790000, 2590000, 1700000, 525000, 4900000, 1589000, 5885000, 1750000, 19200000, 1750000, 325000, 949000, 6850000, 640000, 3149000, 4800000, 1975000, 590000, 394000, 434999, 3000000, 1050000, 320000, 2000000, 6600000, 1775000, 475000, 2150000, 690000, 772000, 872000, 651000, 543000, 658000, 1261000, 585000, 1053000, 746000, 268000, 1243000, 323000, 500000, 725000, 865000, 6100000, 5650000, 8900000, 2175000, 315000, 478000, 243000, 536000, 1124000, 775000, 340000, 351000, 455999, 501999, 1046000, 1130000, 1053000, 790000, 377000, 286000, 1178000, 533000, 350000, 426999, 572000, 998000, 375000, 630000, 376000, 623000, 1613000, 4450000, 1750000, 1575000, 2875000, 1945000, 7150000, 750000, 1273000, 229999, 1375000, 229999, 650000, 425000, 450000, 409999, 90000, 2450000, 518000, 471000, 1024000, 1650000, 589000, 1710000, 1262000, 4050000, 339000, 564000, 275000, 1475000, 982000, 1576000, 560000, 1150000, 444000, 501999, 117000, 2100000, 476000, 332000, 350000, 1425000, 631000, 381000, 3100000, 3675000, 994999, 225000, 890000, 650000, 1585000, 1375000, 4400000, 1875000, 265000, 6000000, 6050000, 434999, 475000, 1300000, 5200000, 265000, 1000000, 4100000, 6100000, 2850000, 925000, 975000, 2350000, 3350000, 10000000, 1850000, 3650000, 700000, 2200000, 2900000, 7400000, 285000, 191000, 19000000, 600000, 590000, 275000, 7450000, 307000, 525000, 190000, 11400000, 1015000, 3500000, 765000, 5100000, 950000, 500000, 85671, 4090000, 210000, 355000, 455000, 4600000, 425000, 3790000, 645000, 1075000, 1600000, 525000, 765000, 1575000, 1190000, 2900000, 1095000, 4400000, 1200000, 475000, 725000, 5800000, 1290000, 441000, 7625000, 4200000, 525000, 6000000, 395000, 1725000, 2290000, 3650000, 875000, 2190000, 3525000, 13000000, 1425000, 1425000, 3975000, 3650000, 2810000, 475000, 894999, 4990000, 699000, 620000, 625000, 4790000, 1250000, 1260000, 221000, 8500000, 450000, 635000, 400000, 3965000, 1800000, 470000, 4475000, 2110000, 3650000, 1889999, 3900000, 483000, 490000, 2975000, 430999, 2580000, 500000, 7150000, 725000, 193000, 900000, 4700000, 575000, 1875000, 675000, 15800000, 606000, 323000, 716000, 158000, 252999, 858000, 6200000, 367000, 324000, 1619000, 775000, 405999, 1063000, 327000, 835000, 440000, 650000, 750000, 1350000, 1600000, 459999, 1100000, 1300000, 790000, 1200000, 320000, 305000, 665000, 975000, 1950000, 680000, 1225000, 950000, 690000, 875000, 2805000, 1680000, 1610000, 1390000, 1260000, 3250000, 2580000, 980000, 1025000, 1025000, 969999, 965000, 955000, 930000, 894999, 855000, 835000, 800000, 800000, 740000, 700000, 605000, 590000, 550000, 565000, 850000, 2000000, 390000, 819999, 750000, 700000, 675000, 370000, 1100000, 990000, 420000, 893000, 865000, 785000, 765000, 755000, 750000, 743000, 730000, 705000, 450000, 699000, 695000, 675000, 675000, 645000, 640000, 1195000, 450000, 580000, 800000, 790000, 1750000, 560000, 635000, 625000, 860000, 990000, 1989999, 280000, 630000, 630000, 2250000, 625000, 290000, 150000, 610000, 2390000, 2700000, 810000, 975000, 150000, 450000, 440000, 780000, 300000, 175000, 4300000, 210000, 2050000, 60000, 385000, 185000, 380000, 1975000, 585000, 1050000, 800000, 825000, 610000, 579000, 785000, 525000, 699000, 799000, 415000, 789000, 785000, 780000, 189000, 269000, 900000, 980000, 1260000, 3050000, 190000, 210000, 195000, 330000, 800000, 2999000, 1450000, 595000, 250000, 1250000, 1275000, 689000, 315000, 700000, 610000, 800000, 600000, 390000, 4099000, 155000, 99000, 335000, 890000, 1825000, 1950000, 1450000, 1500000, 400000, 875000, 850000, 480000, 926000, 600000, 990000, 45000, 2205000, 850000, 969999, 1050000, 2200000, 420000, 2100000, 575000, 484999, 950000, 484999, 1450000, 550000, 1485000, 250000, 2450000, 2650000, 600000, 6500000, 610000, 3300000, 1035000, 4750000, 320000, 2575000, 4950000, 3675000, 1700000, 450000, 430000, 880000, 425000, 525000, 305000, 450000, 1750000, 1300000, 1350000, 1450000, 825000, 1200000, 1500000, 1600000, 1950000, 775000, 2300000, 2550000, 6500000, 2200000, 2400000, 1300000, 1600000, 3750000, 2300000, 5800000, 1500000, 1600000, 4500000, 4000000, 13000000, 4600000, 375000, 850000, 750000, 800000, 850000, 3900000, 4700000, 5000000, 1100000, 7000000, 325000, 250000, 899000, 267000, 525000, 395000, 690000, 850000, 300000, 490000, 670000, 550000, 150000, 400000, 449000, 499000, 290000, 325000, 270000, 1220000, 775000, 2075000, 2490000, 2050000, 1145000, 2075000, 1950000, 1060000, 540000, 6500000, 950000, 175000, 1000000, 825000, 860000, 270000, 800000, 265000, 525000, 576000, 944999, 3250000, 450000, 815000, 532000, 1125000, 725000, 575000, 500000, 975000, 999000, 340000, 215000, 860000, 1525000, 350000, 315000, 190000, 250000, 330000, 590000, 800000, 775000, 700000, 200000, 3150000, 310000, 750000, 550000, 900000, 425000, 490000, 890000, 170000, 490000, 400000, 480000, 320000, 850000, 1490000, 725000, 1039000, 354000, 328000, 270000, 799000, 501000, 95000, 475000, 134000, 340000, 264000, 224000, 295000, 265000, 484999, 463000, 1085000, 3500000, 447000, 1850000, 604000, 252000, 575000, 600000, 400000, 750000, 470000, 1075000, 525000, 398000, 2050000, 599000, 436000, 4500000, 3275000, 950000, 1225000, 1875000, 393000, 325000, 1200000, 1275000, 199000, 300000, 135000, 2185000, 273000, 913000, 593000, 341000, 5200000, 375000, 352000, 271000, 254000, 282000, 575000, 190000, 317000, 238000, 462000, 2418000, 666000, 563000, 479000, 553000, 99205, 1182000, 236000, 367000, 313000, 486000, 121000, 451000, 179000, 1270000, 1750000, 1008000, 566000, 595000, 395000, 2975000, 3000000, 596000, 712000, 1546000, 490000, 112999, 303000, 276000, 256999, 878999, 323000, 1432000, 444000, 54613, 325000, 300000, 249000, 345000, 299000, 325000, 400000, 1750000, 1030000, 669000, 120000, 105000, 650000, 140000, 1650000, 580000, 520000, 1215000, 700000, 550000, 500000, 355000, 150000, 450000, 550000, 1048000, 110000, 350000, 350000, 450000, 750000, 170000, 200000, 921000, 150000, 300000, 235000, 125000, 900000, 260000, 300000, 1500000, 415000, 875000, 450000, 800000, 61000, 130000, 450000, 1100000, 90000, 85000, 130000, 200000, 259000, 300000, 450000, 140000, 525000, 1190000, 2475000, 1711000, 1170000, 2800000, 1875000, 775000, 4400000, 1850000, 250000, 500000, 380000, 950000, 500000, 3300000, 345000, 139000, 711000, 799000, 240000, 285000, 640000, 190000, 700000, 390000, 625000, 250000, 545000, 610000, 595000, 960000, 105000, 630000, 450000, 550000, 640000, 450000, 75000, 261000, 434999, 740000, 570000, 290000, 315000, 625000, 65000, 950000, 80000, 190000, 425000, 200000, 140000, 280000, 100000, 295000, 170000, 409999, 360000, 400000, 170000, 310000, 1700000, 500000, 580000, 650000, 350000, 50000, 550000, 340000, 310000, 250000, 80000, 350000, 390000, 649000, 685000, 2900000, 545000, 550000, 615000, 1420000, 190000, 265000, 1700000, 1500000, 1525000, 1925000, 1113000, 245000, 330000, 535000, 795000, 750000, 170000, 520000, 320000, 570000, 330000, 295000, 375000, 245000, 495000, 341000, 811000, 536000, 298000, 113999, 285000, 715000, 158000, 1828000, 166000, 694000, 649000, 316000, 183000, 528000, 530000, 380000, 1550000, 3656000, 1595000, 275000, 800000, 364000, 3750000, 675000, 449000, 890000, 4200000, 2250000, 3900000, 630000, 1880000, 350000, 2580000, 690000, 650000, 550000, 500000, 525000, 380000, 1750000, 2350000, 400000, 547000, 650000, 420000, 40000, 750000, 265000, 1500000, 500000, 980000, 434999, 470000, 1050000, 380000, 400000, 1250000, 150000, 650000, 725000, 1090000, 850000, 525000, 509999, 360000, 125000, 675000, 229999, 2730000, 670000, 620000, 665000, 450000, 1250000, 680000, 450000, 1150000, 450000, 110000, 1150000, 239000, 750000, 1200000, 785000, 218000, 250000, 1600000, 800000, 752000, 450000, 1280000, 210000, 250000, 1350000, 420000, 130000, 550000, 425000, 610000, 430000, 500000, 390000, 850000, 1120000, 700000, 786000, 100000, 400000, 250000, 409999, 350000, 1100000, 380000, 149000, 165000, 1600000, 750000, 250000, 300000, 630000, 380000, 254999, 1180000, 400000, 720000, 490000, 325000, 595000, 835000, 735000, 395000, 1080000, 325000, 475000, 520000, 750000, 580000, 630000, 1030000, 75000, 259000, 550000, 530000, 700000, 1350000, 450000, 975000, 760000, 250000, 165000, 1550000, 325000, 550000, 680000, 240000, 350000, 1350000, 760000, 140000, 1100000, 700000, 120000, 509999, 710000, 150000, 125000, 250000, 650000, 350000, 545000, 385000, 1150000, 350000, 280000, 395000, 350000, 120000, 80000, 2150000, 595000, 3260000, 1130000, 459999, 500000, 140000, 850000, 160000, 650000, 300000, 295000, 1950000, 450000, 450000, 913000, 60000, 2095000, 680000, 751000, 520000, 765000, 120000, 509999, 100000, 465000, 130000, 99000, 434999, 130000, 160000, 300000, 650000, 70000, 450000, 900000, 750000, 430000, 130000, 99000, 170000, 120000, 130000, 600000, 295000, 560000, 1120000, 75000, 1050000, 880000, 1689999, 430000, 390000, 500000, 830000, 615000, 515000, 430000, 380000, 490000, 803999, 310000, 362000, 475000, 832000, 245000, 831000, 784000, 3

In [ ]:
df['car_prices_in_rupee']=main

In [ ]:
df['car_prices_in_rupee'] = df['car_prices_in_rupee'].astype('int')

In [ ]:
df.head()

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,Jeep Compass 2.0 Longitude Option BSIV,1002999,86226,Diesel,Manual,1,2017,1956,5
1,Renault Duster RXZ Turbo CVT,1283000,13248,Petrol,Automatic,1,2021,1330,5
2,Toyota Camry 2.5 G,1639999,60343,Petrol,Automatic,1,2016,2494,5
3,Honda Jazz VX CVT,777000,26696,Petrol,Automatic,1,2018,1199,5
4,Volkswagen Polo 1.2 MPI Highline,515000,69414,Petrol,Manual,1,2016,1199,5

In [ ]:
df.isnull().sum()

car_name               0
car_prices_in_rupee    0
kms_driven             0
fuel_type              0
transmission           0
ownership              0
manufacture            0
engine                 0
Seats                  0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5512 entries, 0 to 5511
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   car_name             5512 non-null   object
 1   car_prices_in_rupee  5512 non-null   int64
 2   kms_driven           5512 non-null   int64
 3   fuel_type            5512 non-null   object
 4   transmission         5512 non-null   object
 5   ownership            5512 non-null   int64
 6   manufacture          5512 non-null   int64
 7   engine               5512 non-null   int64
 8   Seats                5512 non-null   int64
dtypes: int64(6), object(3)
memory usage: 430.6+ KB

In [ ]:
df

,car_name,car_prices_in_rupee,kms_driven,fuel_type,transmission,ownership,manufacture,engine,Seats
0,Jeep Compass 2.0 Longitude Option BSIV,1002999,86226,Diesel,Manual,1,2017,1956,5
1,Renault Duster RXZ Turbo CVT,1283000,13248,Petrol,Automatic,1,2021,1330,5
2,Toyota Camry 2.5 G,1639999,60343,Petrol,Automatic,1,2016,2494,5
3,Honda Jazz VX CVT,777000,26696,Petrol,Automatic,1,2018,1199,5
4,Volkswagen Polo 1.2 MPI Highline,515000,69414,Petrol,Manual,1,2016,1199,5
...,...,...,...,...,...,...,...,...,...
5507,BMW X1 sDrive 20d xLine,2890000,45000,Diesel,Automatic,1,2018,2995,7
5508,BMW M Series M4 Coupe,6490000,29000,Petrol,Automatic,2,2015,1968,5
5509,Jaguar XF 2.2 Litre Luxury,1375000,90000,Diesel,Automatic,2,2013,2755,5
5510,BMW 7 Series 730Ld,2990000,79000,Diesel,Automatic,3,2015,2967,6
5511,BMW 5 Series 520d M Sport,3190000,42000,Diesel,Automatic,2,2017,1991,5

In [ ]:
df1 = pd.DataFrame(df)
df1.to_excel('/content/drive/MyDrive/old_car_dataset.xlsx', sheet_name = '1')